<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MemoryManagerSetup</AssemblyName>
    <RootNamespace>Ray.MemoryManagerSetup</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <Version>0.9.0-beta.29</Version>
    <FileVersion>0.9.0.29</FileVersion>
    <AssemblyVersion>0.9.0.0</AssemblyVersion>
    <InformationalVersion>0.9.0-beta.29</InformationalVersion>
  </PropertyGroup>
  <ItemGroup><EmbeddedResource Include="Payload\MemoryManager.exe" LogicalName="MemoryManager.exe" /></ItemGroup>
</Project>